// <auto-generated />
using System;
using CommitteeInfrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommitteeInfrastructure.Migrations
{
    [DbContext(typeof(CommitteeContext))]
    [Migration("20251118132558_AddCreatedAt_For_Tables")]
    partial class AddCreatedAt_For_Tables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommitteeCore.Entities.Committee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("Budget")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CreationDecisionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedDecisionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("StatusId");

                    b.ToTable("Committees");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CommitteeMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.ToTable("CommitteeAuditLogs");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DecisionTextArabic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionTextEnglish")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GovernanceModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("MeetingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Outcome")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.ToTable("CommitteeDecisions");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.ToTable("CommitteeDocuments");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Affiliation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContactDetails")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId", "UserId")
                        .IsUnique();

                    b.ToTable("CommitteeMembers");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeMemberRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CommitteeMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeMemberId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_CommitteeMember_Role");

                    b.ToTable("CommitteeMemberRoles");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CommitteeStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 18, 13, 25, 57, 494, DateTimeKind.Utc).AddTicks(2529),
                            Name = "Draft"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 18, 13, 25, 57, 494, DateTimeKind.Utc).AddTicks(3526),
                            Name = "Active"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 18, 13, 25, 57, 494, DateTimeKind.Utc).AddTicks(3528),
                            Name = "Suspended"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 11, 18, 13, 25, 57, 494, DateTimeKind.Utc).AddTicks(3529),
                            Name = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 11, 18, 13, 25, 57, 494, DateTimeKind.Utc).AddTicks(3530),
                            Name = "Dissolved"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 11, 18, 13, 25, 57, 494, DateTimeKind.Utc).AddTicks(3531),
                            Name = "Archived"
                        });
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CommitteeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CommitteeStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DecisionDocumentUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NewStatusId")
                        .HasColumnType("int");

                    b.Property<int>("OldStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommitteeId");

                    b.HasIndex("CommitteeStatusId");

                    b.ToTable("CommitteeStatusHistories");
                });

            modelBuilder.Entity("CommitteeCore.Entities.Committee", b =>
                {
                    b.HasOne("CommitteeCore.Entities.CommitteeStatus", "Status")
                        .WithMany("Committees")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeAuditLog", b =>
                {
                    b.HasOne("CommitteeCore.Entities.Committee", "Committee")
                        .WithMany("CommitteeAuditLogs")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeDecision", b =>
                {
                    b.HasOne("CommitteeCore.Entities.Committee", "Committee")
                        .WithMany("CommitteeDecisions")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeDocument", b =>
                {
                    b.HasOne("CommitteeCore.Entities.Committee", "Committee")
                        .WithMany("CommitteeDocuments")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeMember", b =>
                {
                    b.HasOne("CommitteeCore.Entities.Committee", "Committee")
                        .WithMany("CommitteeMembers")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeMemberRole", b =>
                {
                    b.HasOne("CommitteeCore.Entities.CommitteeMember", "CommitteeMember")
                        .WithMany("CommitteeMemberRoles")
                        .HasForeignKey("CommitteeMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommitteeMember");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeStatusHistory", b =>
                {
                    b.HasOne("CommitteeCore.Entities.Committee", "Committee")
                        .WithMany("CommitteeStatusHistories")
                        .HasForeignKey("CommitteeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommitteeCore.Entities.CommitteeStatus", null)
                        .WithMany("CommitteeStatusHistories")
                        .HasForeignKey("CommitteeStatusId");

                    b.Navigation("Committee");
                });

            modelBuilder.Entity("CommitteeCore.Entities.Committee", b =>
                {
                    b.Navigation("CommitteeAuditLogs");

                    b.Navigation("CommitteeDecisions");

                    b.Navigation("CommitteeDocuments");

                    b.Navigation("CommitteeMembers");

                    b.Navigation("CommitteeStatusHistories");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeMember", b =>
                {
                    b.Navigation("CommitteeMemberRoles");
                });

            modelBuilder.Entity("CommitteeCore.Entities.CommitteeStatus", b =>
                {
                    b.Navigation("CommitteeStatusHistories");

                    b.Navigation("Committees");
                });
#pragma warning restore 612, 618
        }
    }
}
